# Generated by Django 2.2.5 on 2019-09-21 05:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.URLField(blank=True, max_length=300, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Labels_database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FundooNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('note', models.TextField(default='', max_length=1025)),
                ('reminder', models.DateTimeField(default='2019-05-20 10:30:00+00')),
                ('color', models.CharField(max_length=10)),
                ('image', models.TextField(blank=True, null=True)),
                ('archieve', models.BooleanField(default=False)),
                ('is_trash', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 21, 5, 17, 5, 352627))),
                ('modifiedAt', models.DateTimeField(blank=True, null=True)),
                ('collaborator', models.ManyToManyField(blank=True, null=True, related_name='collaborator', to=settings.AUTH_USER_MODEL)),
                ('label', models.ManyToManyField(to='FundooApp.Labels_database')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
