# Generated by Django 2.2.5 on 2019-10-04 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundooApp', '0002_auto_20191004_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundoonotes',
            name='createdAt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 4, 13, 55, 48, 82247)),
        ),
        migrations.AlterField(
            model_name='fundoonotes',
            name='reminder',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 4, 13, 55, 48, 81898), null=True),
        ),
    ]
