# Generated by Django 2.2.5 on 2019-10-05 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundooApp', '0003_auto_20191004_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundoonotes',
            name='color',
            field=models.CharField(blank=True, default='#FFFF', max_length=10),
        ),
        migrations.AlterField(
            model_name='fundoonotes',
            name='createdAt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 5, 6, 29, 59, 751706)),
        ),
        migrations.AlterField(
            model_name='fundoonotes',
            name='image',
            field=models.TextField(blank=True, default='default'),
        ),
        migrations.AlterField(
            model_name='fundoonotes',
            name='reminder',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 5, 6, 29, 59, 751481), null=True),
        ),
    ]
